language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "8"
  - "10"
  - "12"
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run ci:validate
  - npm run ci:test:coverage
after_success:
  - npm run ci:github-release
