// flow-typed signature: d48f6774411d1e88dcc6c9382445b5de
// flow-typed version: <<STUB>>/treeify_v1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'treeify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "treeify" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "treeify/examples/eukaryotes" {
  declare module.exports: any;
}

declare module "treeify/examples/fs_tree" {
  declare module.exports: any;
}

declare module "treeify/test/tree-test" {
  declare module.exports: any;
}

declare module "treeify/treeify" {
  declare module.exports: any;
}

// Filename aliases
declare module "treeify/examples/eukaryotes.js" {
  declare module.exports: $Exports<"treeify/examples/eukaryotes">;
}
declare module "treeify/examples/fs_tree.js" {
  declare module.exports: $Exports<"treeify/examples/fs_tree">;
}
declare module "treeify/test/tree-test.js" {
  declare module.exports: $Exports<"treeify/test/tree-test">;
}
declare module "treeify/treeify.js" {
  declare module.exports: $Exports<"treeify/treeify">;
}
