// flow-typed signature: a88602dc69e8fde7edc7aa06c8f65422
// flow-typed version: <<STUB>>/@discoveryjs/json-ext_v0.5.2/flow_v0.144.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@discoveryjs/json-ext'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@discoveryjs/json-ext" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@discoveryjs/json-ext/dist/json-ext" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/dist/json-ext.min" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/parse-chunked" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/stringify-info" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/stringify-stream-browser" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/stringify-stream" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/text-decoder-browser" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/text-decoder" {
  declare module.exports: any;
}

declare module "@discoveryjs/json-ext/src/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "@discoveryjs/json-ext/dist/json-ext.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/dist/json-ext">;
}
declare module "@discoveryjs/json-ext/dist/json-ext.min.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/dist/json-ext.min">;
}
declare module "@discoveryjs/json-ext/src/index" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src">;
}
declare module "@discoveryjs/json-ext/src/index.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src">;
}
declare module "@discoveryjs/json-ext/src/parse-chunked.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/parse-chunked">;
}
declare module "@discoveryjs/json-ext/src/stringify-info.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/stringify-info">;
}
declare module "@discoveryjs/json-ext/src/stringify-stream-browser.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/stringify-stream-browser">;
}
declare module "@discoveryjs/json-ext/src/stringify-stream.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/stringify-stream">;
}
declare module "@discoveryjs/json-ext/src/text-decoder-browser.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/text-decoder-browser">;
}
declare module "@discoveryjs/json-ext/src/text-decoder.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/text-decoder">;
}
declare module "@discoveryjs/json-ext/src/utils.js" {
  declare module.exports: $Exports<"@discoveryjs/json-ext/src/utils">;
}
